---

- name: zabbix-agent restarted
  command: "/etc/init.d/zabbix-agent restart"
# I had an issue where I get no response from the service. 
# But the agent still worked. It seems this problem occured with a specific version. 
  ignore_errors: yes
